# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='abc', max_length=180)),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Location')),
                ('no_of_staff', models.IntegerField(blank=True, null=True, verbose_name='No.of Employees')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
