# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='abc', max_length=180)),
                ('role', models.CharField(blank=True, max_length=500, null=True, verbose_name='Employee Role')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=500, null=True, verbose_name='Role Name')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Job Openings',
                'ordering': ['-timestamp'],
                'verbose_name': 'Job Opening',
            },
        ),
    ]
