# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_employee_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='abc', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='abc', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Employee Role'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='role',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Role Name'),
        ),
    ]
